import Head from 'next/head'
import { Inter } from 'next/font/google'
import HomePage from "../components/HomePage/HomePage";
import { useEffect } from 'react';
import { getAllWorkers, getPortFolioImages } from '@/Redux/slices/homeSlice';
import { useDispatch, useSelector } from 'react-redux';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const dispatch = useDispatch()
  const alLWorkers = useSelector((store) => store.home.allWorkers);
  const portfolio = useSelector((store) => store.home.portfolio);
  useEffect(() => {
    dispatch(getAllWorkers())
    dispatch(getPortFolioImages())
  }, [])

  return (
    <>
      <Head>
        <title>Good Look </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage tailors={alLWorkers} portfolio={portfolio} />
    </>
  )
}
