import Head from 'next/head'
import { Inter } from 'next/font/google'
import HomePage from "../components/HomePage/HomePage";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
    <Head>
        <title>Good Look </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage/>
    </>
  )
}
